# .github/workflows/az-security-scan.yml

name: AZ-Security-Scan

on:
  push:
    branches:
      - '*'

jobs:
  armourzero_security_test_pre:
    runs-on: ubuntu-latest
    
    env:
      AZ_API_KEY: "${{ secrets.AZ_TOKEN }}"
      PROJECT_KEY: "njSsVvmjPGPYIdbMRmXdnbdsMzsPQjiF"
      BRANCH_NAME: "${{ github.ref_name }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: ArmourZero Security Test (Pre)
        run: |
          docker run -v "$(pwd):/app/wrk" --rm azweming/weming-try:latest --apikey="$AZ_API_KEY" --projectkey="$PROJECT_KEY" --branch="$BRANCH_NAME"
        continue-on-error: true
